export const dataSource = [
  {
    key: 1,
    firstName: "Sarvar",
    lastName: "Akramov",
    subject: "Matematika",
    email: "sarvar.akramov@example.com",
    phone: "+998901234567",
  },
  {
    key: 2,
    firstName: "Dilnoza",
    lastName: "Karimova",
    subject: "Ingliz tili",
    email: "dilnoza.karimova@example.com",
    phone: "+998901234568",
  },
  {
    key: 3,
    firstName: "Abdulloh",
    lastName: "Raxmatullayev",
    subject: "Fizika",
    email: "abdulloh.raxmatullayev@example.com",
    phone: "+998901234569",
  },
  {
    key: 4,
    firstName: "Gulbahor",
    lastName: "Sobirova",
    subject: "Kimyo",
    email: "gulbahor.sobirova@example.com",
    phone: "+998901234570",
  },
  {
    key: 5,
    firstName: "Bahrom",
    lastName: "Tursunov",
    subject: "Tarix",
    email: "bahrom.tursunov@example.com",
    phone: "+998901234571",
  },
  {
    key: 6,
    firstName: "Nigora",
    lastName: "Mirzaeva",
    subject: "Biologiya",
    email: "nigora.mirzaeva@example.com",
    phone: "+998901234572",
  },
  {
    key: 7,
    firstName: "Ulug'bek",
    lastName: "Islomov",
    subject: "Geografiya",
    email: "ulugbek.islomov@example.com",
    phone: "+998901234573",
  },
  {
    key: 8,
    firstName: "Zulfiya",
    lastName: "Abdukarimova",
    subject: "Adabiyot",
    email: "zulfiya.abdukarimova@example.com",
    phone: "+998901234574",
  },
  {
    key: 9,
    firstName: "Jasur",
    lastName: "Nurmatov",
    subject: "Informatika",
    email: "jasur.nurmatov@example.com",
    phone: "+998901234575",
  },
  {
    key: 10,
    firstName: "Dilshoda",
    lastName: "Saidova",
    subject: "Rus tili",
    email: "dilshoda.saidova@example.com",
    phone: "+998901234576",
  },
];

export const studentData = [
  {
    key: 1,
    firstName: "Ali",
    lastName: "Ahmadov",
    grade: "10",
    email: "ali.ahmadov@example.com",
    phone: "+998901234580",
  },
  {
    key: 2,
    firstName: "Sara",
    lastName: "Toshpulatova",
    grade: "11",
    email: "sara.toshpulatova@example.com",
    phone: "+998901234581",
  },
  {
    key: 3,
    firstName: "John",
    lastName: "Doe",
    grade: "9",
    email: "john.doe@example.com",
    phone: "+998901234582",
  },
  {
    key: 4,
    firstName: "Masha",
    lastName: "Ivanova",
    grade: "10",
    email: "masha.ivanova@example.com",
    phone: "+998901234583",
  },
  {
    key: 5,
    firstName: "James",
    lastName: "Smith",
    grade: "12",
    email: "james.smith@example.com",
    phone: "+998901234584",
  },
  {
    key: 6,
    firstName: "Emma",
    lastName: "Johnson",
    grade: "11",
    email: "emma.johnson@example.com",
    phone: "+998901234585",
  },
  {
    key: 7,
    firstName: "Olga",
    lastName: "Petrova",
    grade: "9",
    email: "olga.petrova@example.com",
    phone: "+998901234586",
  },
  {
    key: 8,
    firstName: "Luca",
    lastName: "Miller",
    grade: "10",
    email: "luca.miller@example.com",
    phone: "+998901234587",
  },
  {
    key: 9,
    firstName: "Sophia",
    lastName: "Martinez",
    grade: "12",
    email: "sophia.martinez@example.com",
    phone: "+998901234588",
  },
  {
    key: 10,
    firstName: "Michael",
    lastName: "Brown",
    grade: "11",
    email: "michael.brown@example.com",
    phone: "+998901234589",
  },
  {
    key: 11,
    firstName: "Anna",
    lastName: "Davis",
    grade: "10",
    email: "anna.davis@example.com",
    phone: "+998901234590",
  },
  {
    key: 12,
    firstName: "Alex",
    lastName: "Wilson",
    grade: "9",
    email: "alex.wilson@example.com",
    phone: "+998901234591",
  },
  {
    key: 13,
    firstName: "Kate",
    lastName: "Lee",
    grade: "12",
    email: "kate.lee@example.com",
    phone: "+998901234592",
  },
  {
    key: 14,
    firstName: "Daniel",
    lastName: "Walker",
    grade: "11",
    email: "daniel.walker@example.com",
    phone: "+998901234593",
  },
  {
    key: 15,
    firstName: "Elena",
    lastName: "Taylor",
    grade: "10",
    email: "elena.taylor@example.com",
    phone: "+998901234594",
  },
  {
    key: 16,
    firstName: "Liam",
    lastName: "Anderson",
    grade: "9",
    email: "liam.anderson@example.com",
    phone: "+998901234595",
  },
  {
    key: 17,
    firstName: "Mia",
    lastName: "Thomas",
    grade: "12",
    email: "mia.thomas@example.com",
    phone: "+998901234596",
  },
  {
    key: 18,
    firstName: "Nikita",
    lastName: "Kuznetsov",
    grade: "11",
    email: "nikita.kuznetsov@example.com",
    phone: "+998901234597",
  },
  {
    key: 19,
    firstName: "Sofia",
    lastName: "Martins",
    grade: "10",
    email: "sofia.martins@example.com",
    phone: "+998901234598",
  },
  {
    key: 20,
    firstName: "David",
    lastName: "Nguyen",
    grade: "9",
    email: "david.nguyen@example.com",
    phone: "+998901234599",
  },
  {
    key: 21,
    firstName: "Natalie",
    lastName: "Gonzalez",
    grade: "12",
    email: "natalie.gonzalez@example.com",
    phone: "+998901234600",
  },
  {
    key: 22,
    firstName: "George",
    lastName: "Perez",
    grade: "11",
    email: "george.perez@example.com",
    phone: "+998901234601",
  },
  {
    key: 23,
    firstName: "Aisha",
    lastName: "Rodriguez",
    grade: "10",
    email: "aisha.rodriguez@example.com",
    phone: "+998901234602",
  },
  {
    key: 24,
    firstName: "Oliver",
    lastName: "Williams",
    grade: "9",
    email: "oliver.williams@example.com",
    phone: "+998901234603",
  },
  {
    key: 25,
    firstName: "Chloe",
    lastName: "White",
    grade: "12",
    email: "chloe.white@example.com",
    phone: "+998901234604",
  },
];
